"""Unofficial Python client for the Zend messaging platform."""

from zend.client.error import (
    APIError,
    ApplicationError,
    AuthenticationError,
    BadRequestError,
    NotFoundError,
    PermissionDeniedError,
    RateLimitError,
    ServerError,
    ZendError,
    ZendTimeoutError,
)
from zend.common.types import (
    ListParams,
    ZendFailure,
    ZendResponse,
    ZendSuccess,
    is_success,
)
from zend.resources.emails.types import (
    Email,
    EmailAttachment,
    EmailList,
    SendEmailOptions,
)
from zend.resources.messages.types import (
    BulkMessageItem,
    BulkMessageOptions,
    BulkMessageResult,
    Channel,
    DeliveryAttempt,
    DeliveryPriority,
    Message,
    MessageList,
    MessageStatus,
    Priority,
    SendMessageOptions,
    SendMessageResult,
)
from zend.resources.templates.types import (
    ListTemplatesParams,
    Template,
    TemplateChannelVariant,
    TemplateList,
    TemplateVariable,
)
from zend.resources.voice.types import (
    SendVoiceOptions,
    VoiceBatch,
    VoiceBatchDetail,
    VoiceBatchList,
    VoiceCounts,
    VoiceFallback,
    VoiceGender,
    VoiceRecipient,
    VoiceSendResult,
    VoiceUpload,
)
from zend.version import VERSION, __version__
from zend.zend import AsyncZend, Zend

__all__ = [
    "VERSION",
    "APIError",
    "ApplicationError",
    "AsyncZend",
    "AuthenticationError",
    "BadRequestError",
    "BulkMessageItem",
    "BulkMessageOptions",
    "BulkMessageResult",
    "Channel",
    "DeliveryAttempt",
    "DeliveryPriority",
    "Email",
    "EmailAttachment",
    "EmailList",
    "ListParams",
    "ListTemplatesParams",
    "Message",
    "MessageList",
    "MessageStatus",
    "NotFoundError",
    "PermissionDeniedError",
    "Priority",
    "RateLimitError",
    "SendEmailOptions",
    "SendMessageOptions",
    "SendMessageResult",
    "SendVoiceOptions",
    "ServerError",
    "Template",
    "TemplateChannelVariant",
    "TemplateList",
    "TemplateVariable",
    "VoiceBatch",
    "VoiceBatchDetail",
    "VoiceBatchList",
    "VoiceCounts",
    "VoiceFallback",
    "VoiceGender",
    "VoiceRecipient",
    "VoiceSendResult",
    "VoiceUpload",
    "Zend",
    "ZendError",
    "ZendFailure",
    "ZendResponse",
    "ZendSuccess",
    "ZendTimeoutError",
    "__version__",
    "is_success",
]
